### PR TITLE
Add gas optimization by implementing onlyApprovedOrOwner modifier

### PR DESCRIPTION
**Pull request by sennett-lau**

### CODE REVIEW

**Comment by cygaar** [comment]
Do you have a comparison of the before and after of these changes?

**Comment by sennett-lau** [comment]
Here is the comparison of the gas snapshot, I'm also wondering if this is a successful gas optimization, please let me know if there is any comment!

ERC5643Test:testCancelNotOwner() (gas: 17875 → 17839) -36
ERC5643Test:testCancelValid() (gas: 20777→ 20782) +5
ERC5643Test:testExpiresAt() (gas: 42729 → 42737) +8
ERC5643Test:testExpiresAtInvalidToken() (gas: 12901 → 12901) ±0
ERC5643Test:testExtendSubscriptionInvalidToken() (gas: 13039 → 13039) ±0
ERC5643Test:testIsRenewableInvalidToken() (gas: 12831 → 12831)  ±0
ERC5643Test:testRenewalDurationTooLong() (gas: 47961 → 47964) +3
ERC5643Test:testRenewalDurationTooShort() (gas: 47664 → 47667) +3
ERC5643Test:testRenewalExistingSubscription() (gas: 145068 → 145076) +8
ERC5643Test:testRenewalInsufficientPayment() (gas: 26874 → 26877) +3
ERC5643Test:testRenewalInvalidTokenId() (gas: 22316 → 22319) +3
ERC5643Test:testRenewalNewSubscription() (gas: 53086 → 53091) +5
ERC5643Test:testRenewalNotOwner() (gas: 17997 → 17964) -33

**Comment by cygaar** [comment]
It actually adds gas to more functions than it doesn't. Don't use the total gas change as the heuristic to judge your change off of since that value is dependent on the specific test cases you have.

In your case, I actually think this change hurts overall gas usage.

**Comment by sennett-lau** [comment]
Thanks for your comments, will just close this PR instead.

**Pull request closed without merging**
